--%%%%%%%%%%%%%%%%%%%%%% -------------------------------------%%%%%%%%%%%%%
-- STORED ROUTINES
--%%%%%%%%%%%%%%%%%%%%%% -------------------------------------%%%%%%%%%%%%%
-- TYPES of STORED ROUTINES : Stored procedures (procedures) AND Functions